name: Build XIVLauncher AppImage

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04

    steps:
      
      - uses: actions/checkout@v4
      - name: Packaging
        run: |
          apt update
          # ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
          DEBIAN_FRONTEND=noninteractive apt install -y fuse curl sudo apt-utils modprobe
          # dpkg-reconfigure --frontend noninteractive tzdata
          modprobe fuse
          ./make-appimage.sh
        
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: XIVLauncher-AppImage
          path: XIVLauncher-AppImage.tar.gz