name: Build XIVLauncher AppImage

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4
      - name: Packaging
        run: |
          sudo apt update
          sudo apt install fuse curl
          ./make-appimage.sh
        
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: XIVLauncher-AppImage
          path: xivlauncher/
